version: "3.8"

services:
  db_postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: voting_system
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    depends_on:
      - db_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_LISTEN_PORT: 80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge